export default [{
        id:1,
        title: "belanja bulanan",
        tag: "blue",
        time: "09:00",
        date: "2020-11-08",
        status: false,
    },
    {
        id:2,
        title: "meeting dengan client",
        tag: "green",
        time: "13:00",
        date: "2020-10-09",
        status: true,
    },
    {
        id:3,
        title: "nongki",
        tag: "green",
        time: "20:00",
        date: "2020-11-10",
        status: false,
    },
    {
        id:4,
        title: "survey kos-kosan",
        tag: "blue",
        time: "18:00",
        date: "2020-10-14",
        status: false,
    },
    {
        id:5,
        title: "update sosmed jualan",
        tag: "blue",
        time: "09:00",
        date: "2020-10-14",
        status: false,
    },
    {
        id:6,
        title: "masak sarden",
        tag: "blue",
        time: "13:00",
        date: "2020-11-10",
        status: true,
    },
    {
        id:7,
        title: "setor uang ke bank",
        tag: "brown",
        time: "15:00",
        date: "2020-10-14",
        status: false,
    },
    {
        id:8,
        title: "ketemu client tambang",
        tag: "green",
        time: "10:00",
        date: "2020-10-12",
        status: true,
    },
    {
        id:9,
        title: "undangan nikah",
        tag: "green",
        time: "18:00",
        date: "2020-11-09",
        status: false,
    },
    {
        id: 10,
        title: "jemput teman di bandara",
        tag: "brown",
        time: "09:00",
        date: "2020-11-12",
        status: false,
    }
]